catalog/urls.py
from django.urls import path

from catalog import views

urlpatterns = [
    path('', views.index,name='index'),
    path('books/',views.BookListView.as_view(),name="books"),
    path('authors',views.AuthorListView.as_view(),name='authors'),
    path('author/<int:pk>',views.AuthorDetailView.as_view(),name='author-detail'),
    path('book/<int:pk>',views.BookDetailView.as_view(),name='book-detail'),
]

locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('catalog/', include('catalog.urls')),
                  path('', RedirectView.as_view(url='/catalog/', permanent=True)),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid

from django.db import models
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from django.urls import reverse


# Create your models here.

class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book  genre (e.g. Science fiction,French poetry ..."
    )

    def __str__(self):
        """ Returns a string representation of the genre """
        return self.name

    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message="A genre with that name already exists.",
            ),
        ]


class Book(models.Model):
    title = models.CharField(
        max_length=50,
        help_text="Enter the title for the book",
    )
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(
        help_text="Enter the summary of the book ",
        max_length=1000
    )
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genres = models.ManyToManyField(Genre, help_text="select a genre for this book")
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """ Returns a string representation of the book"""
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genres.all()[:3])
    
    display_genre.short_description = 'Genre'
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True,
                          help_text="Unique ID for this particular book")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m',
                              help_text='Book availability status')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.last_name} {self.first_name} '

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class Language(models.Model):
    language_name = models.CharField(max_length=50,unique=True)

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('language_name'),
                name='language_case_insensitive_unique',
                violation_error_message="A Language with that name already exists",
            ),

        ]
        ordering = ['language_name']

    def __str__(self):
        return f'{self.language_name}'

    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])

catalog/views.py
from django.shortcuts import render
from .models import Author, Book ,BookInstance ,Genre
from django.views import generic
# Create your views here.
def index(request):
    """view function for the home page of the site"""
    num_books =  Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()
    num_genres=Genre.objects.count()
    num_books_containing_the= Book.objects.filter(title__icontains="The").count()
    context={
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_available':num_instances_available,
        'num_authors':num_authors,
        'num_books_containing_the':num_books_containing_the,
        'num_genres':num_genres
    }
    return render(request,'index.html',context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2
class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    
class AuthorDetailView(generic.DetailView):
    model = Author
    

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'books' %}">All books</a></li>
            <li><a href="{% url 'authors' %}">All authors</a></li>
          </ul>
          {% endblock %} 
          {% block pagination %} 
          {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              {% if page_obj.has_previous %}
              <a
                href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                >previous</a
              >
              {% endif %}
              <span class="page-current">
                Page {{ page_obj.number }} of {{page_obj.paginator.num_pages}}.
              </span>
              {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                >next</a
              >
              {% endif %}
            </span>
          </div>
          {% endif %} {% endblock %}
        </div>
        <div class="col-sm-10">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %} {% block content %}
<h1>Author:{{ author.first_name }}, {{ author.last_name }}</h1>

<p>
  {{ author.date_of_birth }} - {% if author.date_of_death %} {{author.date_of_death }} {% endif %}
</p>
<ul>
  {% for book in author.book_set.all %}
  <strong>
    <a href="{{ book.get_absolute_url }}">
      {{ book.title }}</li>
    </a> ({{ book.bookinstance_set.all.count }})
  </strong>
  <p>{{ book.summary }}</p>
  {% empty %}
  <li>No books available.</li>
  {% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{% url 'author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No authors are available.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %} {% block content %}
<h1>Title: {{ book.title }}</h1>

<p>
  <strong>Author:</strong>
  <a href="{{book.author.get_absolute_url}}">{{ book.author}}</a>
</p>
<!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genres.all|join:", " }}</p>

<div style="margin-left: 20px; margin-top: 20px">
  <h4>Copies</h4>

  {% for copy in book.bookinstance_set.all %}
  <hr />
  <p
    class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"
  >
    {{ copy.get_status_display }}
  </p>
  {% if copy.status != 'a' %}
  <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
  {% endif %}
  <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
  <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
  {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{book.get_absolute_url}}">{{ book.title }}</a>
        ({{book.author}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}
 {% block title %}
<title>home page</title>
{%endblock%} 
{% block content %}
  <h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>genres:</strong> {{ num_genres }}</li>
    <li><strong>num books containing the:</strong> {{ num_books_containing_the }}</li>
  </ul>
{% endblock %}